baseurl                 = "http://www.talcrafts.com/"
languageCode            = "en-us"
title                   = "TalCrafts Blog"
theme                   = "hugo-phlat-theme"

[permalinks]
    post                = "/:year/:month/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"

# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"

[[menu.header]]
    name                = "About"
    weight              = 3
    url                 = "/about/"

# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
[[menu.footer]]
    name                = "Privacy Policy"
    weight              = 1
    url                 = "/privacy-policy/"

[params]
    keywords            = ["default", "keywords", "if", "no", "front", "matter"]
    description         = "A blog for whatever we are learning in our day to day activity"
    google_analytics    = "UA-93463562-1"
    google_adsense      = "ca-pub-XXXXXX"
    disqus              = "talcraft-blog"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://www.twitter.com/ahmad_imt"
    googleplus          = "https://plus.google.com/NAME_HERE"
    linkedin            = "https://www.linkedin.com/in/NAME_HERE"
    youtube             = "https://www.youtube.com/users/NAME_HERE"
    paypal              = "https://paypal.me/NAME_HERE"
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""
