+++
date = "2017-03-22T20:56:25+05:30"
title = "Elasticsearch Dynamic Mapping"
categories = ["Elasticsearch"]
tags = ["Elasticsearch"]
author = "Imteyaz Ahmad"
description = "This blog talks about Elasticsearch dynamic templates"
draft = false

+++

*Introduction*

In Elasticsearch, it is not neccessary to create an index, define mapping before hand and then index a document. For example, We can create a document of type `post` in an index called `blog` in Elasticseach by just firing following command:

<!--more-->

[source,json]
----
PUT blog/post/1
{
  "author": "Imteyaz",
  "age": 30,
  "post_date": "2017-03-21",
  "description": "2017-03-21"
}
----

Elasticsearch automatically detects and add new types and fields. This is called _dynamic mapping_. It is a great feature as it helps in getting started fast. However this can be problematic sometimes. Let's have a look on the _mapping_ generated by Elasticsearch for the document.

[source,json]
----
GET blog/_mapping
// Result
{
  "blog": {
    "mappings": {
      "post": {
        "properties": {
          "age": {
            "type": "long"
          },
          "author": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "description": {
            "type": "date"
          },
          "post_date": {
            "type": "date"
          }
        }
      }
    }
  }
}
----

Here, the type of `description` field is `date` which is not desired. To prevent such thing, we can either disable `date_detection` or we can define a custom dynamic template.

*Disable Date Detection*

Dynamic date detection can be disbled by setting `date_detection` to `false`

[source,json]
----
PUT blog/_mapping/post
{
    "date_detection": false
}
----

*Define Custom Template*

We can define our own dynamic template and create it as shown below:

[source,json]
----
PUT _template/idx_template
{
    "template": "blog*",
    "settings": {
        "number_of_shards": 5,
        "number_of_replicas": 1
    },
    "analysis": {
        "analyzer": {
            "mc_analyzer": {
                "type": "standard",
                "stopwords": "_english_"
            }
        }
    },
    "mappings": {
        "post": {
          "date_detection": false,
            "dynamic_templates": [{
                "date_fields": {
                    "match": "*_date",
                    "mapping":{
                        "type": "date"
                    }
                }

            }]
        }
    }
}
----

This template applies to any index whose name start with `blog`. Here we have disabled date detection and explicitely mapping our field as date that contains `_date` in it.

Now let us create the `blog` index again and see the mapping generated.

[source,json]
----
PUT blog/post/1
{
  "author": "Imteyaz",
  "age": 30,
  "post_date": "2017-03-21",
  "description": "2017-03-21"
}
----

Below is the new mapping generated by Elasticsearch:

[source.json]
----
{
  "blog": {
    "mappings": {
      "post": {
        "dynamic_templates": [
          {
            "date_fields": {
              "match": "*_date",
              "mapping": {
                "type": "date"
              }
            }
          }
        ],
        "date_detection": false,
        "properties": {
          "age": {
            "type": "long"
          },
          "author": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "description": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "post_date": {
            "type": "date"
          }
        }
      }
    }
  }
}
----

In the new mapping created, the  `description` field is a `text` and `post_date` is a `date` field.


*Conclusion*

It's better to create a template for index if we don't know new fields to be added in future and if somehow we can control the field name.


*References*

- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
- https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
